name: translate_app
description: A comprehensive translation app with voice, camera, and conversation features
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5

  # UI & Animations
  flutter_animate: ^4.5.0
  lottie: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  gap: ^3.0.1
  glassmorphism: ^3.0.0
  card_swiper: ^3.0.1
  flutter_slidable: ^4.0.0

  # Networking
  dio: ^5.3.2
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1

  # Localization
  easy_localization: ^3.0.3

  # Speech & Audio
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.0+1

  # Camera & OCR
  camera: ^0.11.1
  google_ml_kit: ^0.20.0
  image_picker: ^1.0.4

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.3.0

  # Utils
  dartz: ^0.10.1
  uuid: ^4.1.0
  intl: ^0.20.2
  auto_route: ^9.3.0+1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # Development
  json_annotation: ^4.8.1
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  shadcn_ui: ^0.27.1
  go_router: ^15.1.3
  skeletonizer: ^2.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  auto_route_generator: ^9.0.0

  # Testing
  mocktail: ^1.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/flags/
    - assets/translations/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
